name: MLP Streamlit CI/CD

on:
  push:
    branches:
      - main  # or 'master' based on your branch name
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn streamlit pyngrok joblib

      - name: Train and Save Model
        run: |
          python untitled9.py  # This will train MLP, save model and scaler

      - name: Start Streamlit App (local)
        run: |
          nohup streamlit run app.py &

      

